# Generated by Django 6.0.3 on 2026-05-05 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-booking_time']},
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bus',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('user', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('bus', 'seat_number')},
        ),
    ]
